version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for source NuGet packages
  - package-ecosystem: "nuget"
    directory: "Source/"
    schedule:
      interval: "weekly"
    target-branch: "release"
      
  # Maintain dependencies for test NuGet packages
  - package-ecosystem: "nuget"
    directory: "Tests/"
    schedule:
      interval: "weekly"
    target-branch: "release"
