version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    target-branch: "staging"

  # Maintain dependencies for source NuGet packages
  - package-ecosystem: "nuget"
    directory: "Source/"
    groups:
      source-nuget:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    target-branch: "staging"

  # Maintain dependencies for test NuGet packages
  - package-ecosystem: "nuget"
    directory: "Tests/"
    groups:
      tests-nuget:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    target-branch: "staging"
